language: node_js
node_js:
- '0.10'
before_script:
- npm install
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#jsbin
deploy:
  provider: heroku
  app: jsbin-learn
  on: master
  api_key:
    secure: OlayijMgdoB7zJQaKiv7SKaXPZeDy+Nn7azh87+lb6kd4nh/lDS8+Ym8mKFIdFMQTVwpfU57sg+XO8QErKLN4esct5+kVvLFBhzJIy1XG3DGXaYHyoXmonLostD9aZx9imJC3BENmG28l3HV5NKotNixIhmsB/Qlot5Ex801QtM=
