baseURL = "/"
languageCode = "en-gb"
title = "JS Bin help"
googleAnalytics = "UA-1656750-13"
pygmentsCodeFences = true
pygmentsStyle = "vs"

[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
